use crate::types::*;
use crate::{StorageKey, TlaRegistry, PRODUCTION_LEASE_TERM_NS};
use near_sdk::near;
use near_sdk::store::{IterableMap, IterableSet, LookupMap, Vector};
use near_sdk::AccountId;

#[near(serializers = [borsh])]
pub struct TlaRegistryV1 {
    pub state_version: u16,
    pub tlas: IterableMap<AccountId, TlaEntry>,
    pub sub_accounts: IterableMap<String, SubAccountEntry>,
    pub sub_accounts_by_owner: LookupMap<AccountId, IterableSet<String>>,
    pub sub_accounts_by_tla: LookupMap<AccountId, IterableSet<String>>,
    pub recent_activity: Vector<ActivityRecord>,
    pub activity_cursor: u32,
    pub admins: IterableSet<AccountId>,
    pub fee_config: FeeConfig,
    pub total_revenue: u128,
    pub sub_account_count: u64,
    pub paused: bool,
    pub version: u8,
    pub pending_refunds: LookupMap<AccountId, u128>,
    pub total_pending_refunds: u128,
    pub ft_allowlist: IterableSet<AccountId>,
    pub business_sub_count: LookupMap<AccountId, u32>,
    pub business_sub_cap_override: LookupMap<AccountId, u32>,
    pub parked_names: LookupMap<String, ParkedEntry>,
    pub reclaim_pending: LookupMap<String, bool>,
    pub payment_authorities: IterableSet<AccountId>,
    pub recovery_authorities: IterableSet<AccountId>,
    pub hos_extension: AccountId,
    pub grace_period_ns: u64,
    pub price_oracle: AccountId,
    pub near_usd_rate_micro: u128,
    pub rate_updated_at: u64,
    pub rate_sequence: u64,
    pub treasury: AccountId,
    pub council: AccountId,
    pub marketplace_paused: bool,
    pub paused_until_ns: u64,
    pub unpaused_at: u64,
    pub sweepable_tokens: IterableSet<AccountId>,
    pub suspended_until: LookupMap<AccountId, u64>,
    pub nft_contract_metadata: NftContractMetadata,
    pub approved_code_hash: Option<[u8; 32]>,
    pub approved_at: Option<u64>,
    pub upgrade_delay_ns: u64,
    pub venues: IterableSet<AccountId>,
    pub upgrade_proven: bool,
}

impl From<TlaRegistryV1> for TlaRegistry {
    fn from(old: TlaRegistryV1) -> Self {
        Self {
            state_version: crate::STATE_VERSION,
            tlas: old.tlas,
            sub_accounts: old.sub_accounts,
            sub_accounts_by_owner: old.sub_accounts_by_owner,
            sub_accounts_by_tla: old.sub_accounts_by_tla,
            recent_activity: old.recent_activity,
            activity_cursor: old.activity_cursor,
            admins: old.admins,
            fee_config: old.fee_config,
            total_revenue: old.total_revenue,
            sub_account_count: old.sub_account_count,
            paused: old.paused,
            version: old.version,
            pending_refunds: old.pending_refunds,
            total_pending_refunds: old.total_pending_refunds,
            ft_allowlist: old.ft_allowlist,
            business_sub_count: old.business_sub_count,
            business_sub_cap_override: old.business_sub_cap_override,
            parked_names: old.parked_names,
            reclaim_pending: old.reclaim_pending,
            payment_authorities: old.payment_authorities,
            recovery_authorities: old.recovery_authorities,
            hos_extension: old.hos_extension,
            grace_period_ns: old.grace_period_ns,
            lease_term_ns: PRODUCTION_LEASE_TERM_NS,
            price_oracle: old.price_oracle,
            near_usd_rate_micro: old.near_usd_rate_micro,
            rate_updated_at: old.rate_updated_at,
            rate_sequence: old.rate_sequence,
            treasury: old.treasury,
            council: old.council,
            marketplace_paused: old.marketplace_paused,
            paused_until_ns: old.paused_until_ns,
            unpaused_at: old.unpaused_at,
            sweepable_tokens: old.sweepable_tokens,
            suspended_until: old.suspended_until,
            nft_contract_metadata: old.nft_contract_metadata,
            approved_code_hash: old.approved_code_hash,
            approved_at: old.approved_at,
            upgrade_delay_ns: old.upgrade_delay_ns,
            venues: old.venues,
            upgrade_proven: old.upgrade_proven,
            paid_order_ids: LookupMap::new(StorageKey::PaidOrderIds),
            pending_council: None,
            pending_council_at: None,
        }
    }
}
